### ISSUE TITLE
Can you share the output tensor names?

### ISSUE THREAD

**Issue by xxjdxmt** [qyxqyx/AIM_FAS#1]
Thank for your share!
I want to convert saved model ( data-00000-of-00001, .index, .meta) to .pb file. Can you share the output tensor node names? In model.py file, it seems the mean value of several outputs is used as final predict result.

**Comment by qyxqyx** [comment]
Thanks.
The model can not be tested directly. If you want to test the meta-learner on OULU-ZF, you should first pre-train a model on OULU-ZF and then train the meta-learner based on the pre-trained model.
The final performance of the trained meta-learner is the averaged performance on all testing tasks.
