### ISSUE TITLE
Question about the definition of FAR, FRR

### ISSUE THREAD

**Issue by ZhangYuanhan-AI** [qyxqyx/AIM_FAS#3]
Thanks for your share!
Here are some question about the definition of FAR, FRR and HTER.
In AIM_FAS
FAR = FP / (FP + TP)
FRR = FN / (TN + FN)
HTER = (FAR + FRR) / 2
However in CDCN
https://github.com/ZitongYu/CDCN/tree/ccad225c72381536db6eb911b5ab9b8f2122dfd9
FAR = FP / (FP + TN)   which equals to FPR
FRR = FN / (TP + FN)     which equals to (1- TPR)
HTER = (FAR + FRR) / 2
Which definition is correct？
Thanks for your replying!

**Comment by qyxqyx** [comment]
Thanks for your question.  
FAR = FP / (FP + TN) and FRR = FN / (TP + FN). 
Only APCER, NPCER(BPCER), and ACER were used to evaluate our method and we have deleted all useless metrics to make our code clear.

**Comment by ZhangYuanhan-AI** [comment]
Thanks for your replying!
